# LQG Volume Quantization Controller Configuration
# ==============================================

# Physical Constants
physics:
  planck_length: 1.616e-35  # m
  planck_time: 5.391e-44    # s
  planck_mass: 2.176e-8     # kg
  immirzi_gamma: 0.2375     # Barbero-Immirzi parameter
  hbar: 1.055e-34          # Reduced Planck constant

# SU(2) Representation Parameters
su2:
  min_j: 0.5               # Minimum SU(2) representation
  max_j: 10.0              # Maximum SU(2) representation
  precision: 1.0e-12       # Numerical precision for j optimization
  scheme: "analytical"     # Options: analytical, closed_form, generating_functional, asymptotic
  cache_enabled: true      # Enable computation caching
  cache_size: 1000        # Maximum cache size

# Volume Quantization Parameters
volume_quantization:
  mode: "production"       # Options: standard, enhanced, production, validation
  tolerance: 1.0e-15      # Volume computation tolerance
  max_patches: 10000      # Maximum number of active patches
  patch_lifetime: 1.0e-40 # Maximum patch lifetime (s)

# Uncertainty Quantification
uncertainty:
  base_uncertainty: 1.0e-45      # Base volume uncertainty (m³)
  scale_adaptation_factor: 0.1   # Scale adaptation coefficient
  enable_adaptive_bounds: true   # Enable scale-adaptive uncertainty bounds

# Constraint Monitoring
constraints:
  monitoring_enabled: true       # Enable real-time constraint monitoring
  violation_threshold: 1.0e-6   # Constraint violation threshold
  runtime_checks: true          # Enable runtime algebra checks

# Polymer Quantization
polymer:
  scheme: "production"           # Options: standard, improved, sinc_enhanced, production
  mu_optimal: 0.7               # Optimal polymer scale parameter
  enhancement_factor: 2.42e10   # 24.2 billion× enhancement
  sinc_correction: true         # Enable sinc(πμ) correction
  holonomy_correction: true     # Enable sin(μδ)/δ corrections

# LQG Integration
lqg_integration:
  unified_lqg_enabled: true     # Enable unified-lqg integration
  unified_lqg_qft_enabled: true # Enable unified-lqg-qft integration
  polymer_field_enabled: true   # Enable lqg-polymer-field-generator integration
  fallback_mode: "analytical"   # Fallback computation mode

# Performance Settings
performance:
  parallel_processing: true     # Enable parallel processing where possible
  optimization_level: 2        # Optimization level (0-3)
  memory_limit_mb: 1000        # Memory limit in MB
  computation_timeout: 30.0    # Computation timeout in seconds

# Logging Configuration
logging:
  level: "INFO"                # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: true           # Enable logging to file
  file_path: "lqg_volume_quantization.log"
  console_enabled: true        # Enable console logging

# Validation Settings
validation:
  comprehensive_checks: true   # Enable comprehensive validation
  numerical_stability_tests: true # Enable numerical stability testing
  integration_tests: true     # Enable integration testing
  performance_benchmarks: true # Enable performance benchmarking

# Production Settings
production:
  safety_checks: true          # Enable production safety checks
  error_recovery: true         # Enable automatic error recovery
  monitoring_interval: 1.0    # Monitoring interval in seconds
  backup_enabled: true         # Enable automatic state backup
  backup_interval: 300.0      # Backup interval in seconds

# Visualization Settings
visualization:
  plotting_enabled: true       # Enable plotting capabilities
  figure_size: [12, 8]        # Default figure size
  dpi: 300                    # Plot resolution
  save_format: "png"          # Save format: png, pdf, svg
  colormap: "viridis"         # Default colormap

# Testing Configuration
testing:
  unit_tests: true            # Enable unit tests
  integration_tests: true     # Enable integration tests
  performance_tests: true     # Enable performance tests
  stress_tests: false         # Enable stress tests (resource intensive)
  test_data_path: "test_data/" # Path for test data files
